default: &default
  adapter: postgresql
  encoding: unicode
  encoding: unicode
  pool:     5
  database: <%= ENV['SOUP_DATABASE'] %>
  username: <%= ENV['SOUP_DATABASE_USERNAME'] %>
  password: <%= ENV['SOUP_DATABASE_PASSWORD'] %>


development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default
  database: soup_test

production:
  <<: *default
