# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: a4d1b96ef32c0f94e603ba99dc495c5342c9e2d6565304fcd264eb6f03295d9e42d59416f012182d66f230714c0b229697137bb4541d5b83e82e952a593693bf

test:
  domain_name: example.com 
  secret_key_base: 5b1357a21c1489d24a532e112617add0c137402d171574b14045cf150bf52a0bf613a1c23d7b73c27b79877ce96d4176604e2d16d2ee557ba1c9b964386de380

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
